// Generated-art registry. Only entries listed here have real art; everything
// else keeps using the emoji/CSS placeholder so the game never breaks while
// art is still being generated in batches.

window.DS = window.DS || {};

(function () {
  const BASE = 'assets/';

  const REGISTRY = {
    portraits: {
      chosen_undead: 'portraits/chosen_undead.png',
      artorias: 'portraits/artorias.png',
      hollow_soldier: 'portraits/hollow_soldier.png',
      hollow_archer: 'portraits/hollow_archer.png',
      asylum_demon: 'portraits/asylum_demon.png',
      skeleton: 'portraits/skeleton.png',
      rat_swarm: 'portraits/rat_swarm.png',
      painting_guardian: 'portraits/painting_guardian.png',
      balder_knight: 'portraits/balder_knight.png',
      silver_knight: 'portraits/silver_knight.png',
      channeler: 'portraits/channeler.png',
      darkwraith: 'portraits/darkwraith.png',
      crystal_golem: 'portraits/crystal_golem.png',
      royal_sentinel: 'portraits/royal_sentinel.png',
      necromancer: 'portraits/necromancer.png',
      taurus_demon: 'portraits/taurus_demon.png',
      capra_demon: 'portraits/capra_demon.png',
      bell_gargoyle: 'portraits/bell_gargoyle.png',
      gaping_dragon: 'portraits/gaping_dragon.png',
      ornstein: 'portraits/ornstein.png',
      solaire: 'portraits/solaire.png',
      oscar: 'portraits/oscar.png',
      quelaag: 'portraits/quelaag.png',
      gwyn: 'portraits/gwyn.png',
      smough: 'portraits/smough.png',
      nito: 'portraits/nito.png',
      manus: 'portraits/manus.png',
      seath: 'portraits/seath.png',
      priscilla: 'portraits/priscilla.png',
      fourkings: 'portraits/fourkings.png',
      havel: 'portraits/havel.png',
      siegmeyer: 'portraits/siegmeyer.png',
      lautrec: 'portraits/lautrec.png',
      petrus: 'portraits/petrus.png',
      laurentius: 'portraits/laurentius.png',
      gwynevere: 'portraits/gwynevere.png',
      ciaran: 'portraits/ciaran.png',
      quelana: 'portraits/quelana.png',
      sif: 'portraits/sif.png',
      logan: 'portraits/logan.png',
      gwyndolin: 'portraits/gwyndolin.png',
      gough: 'portraits/gough.png',
      ornstein_boss: 'portraits/ornstein.png',
      smough_boss: 'portraits/smough.png',
      gwyn_boss: 'portraits/gwyn.png',
      quelaag_boss: 'portraits/quelaag.png',
      nito_boss: 'portraits/nito.png',
      manus_boss: 'portraits/manus.png',
      seath_boss: 'portraits/seath.png',
      fourkings_boss: 'portraits/fourkings.png',
      artorias_boss: 'portraits/artorias.png',
      priscilla_boss: 'portraits/priscilla.png',
      ceaseless_discharge: 'portraits/ceaseless_discharge.png',
      kalameet: 'portraits/kalameet.png',
      bed_of_chaos: 'portraits/bed_of_chaos.png',
      capra_demon_hound: 'portraits/capra_demon_hound.png',
      bed_of_chaos_left_arm: 'portraits/bed_of_chaos_left_arm.png',
      bed_of_chaos_right_arm: 'portraits/bed_of_chaos_right_arm.png',
      everlasting_dragon: 'portraits/everlasting_dragon.png',
      witch_of_izalith: 'portraits/witch_of_izalith.png',
      way_of_white_knights: 'portraits/way_of_white_knights.png',
      hollowed_solaire: 'portraits/hollowed_solaire.png',
      gwyndolin_boss: 'portraits/gwyndolin_boss.png',
      darkwraith_knights: 'portraits/darkwraith_knights.png',
      sleeping_giant: 'portraits/sleeping_giant.png',
      devourer: 'portraits/devourer.png',
      twin_horned_wretch: 'portraits/twin_horned_wretch.png',
      sky_strung_wraith: 'portraits/sky_strung_wraith.png',
      shroud_bat: 'portraits/shroud_bat.png',
      humanity: 'portraits/humanity.png',
      star_eater: 'portraits/star_eater.png',
      rotguard_sentinel: 'portraits/rotguard_sentinel.png',
      bloomfed_hound: 'portraits/bloomfed_hound.png',
      rustbound_archer: 'portraits/rustbound_archer.png',
      barrow_gnawer: 'portraits/barrow_gnawer.png',
      unblinking_choir: 'portraits/unblinking_choir.png',
      maw_of_the_deep_dark: 'portraits/maw_of_the_deep_dark.png',
      withered_bloom: 'portraits/withered_bloom.png',
      thousandfold: 'portraits/thousandfold.png',
      cooling_heart: 'portraits/cooling_heart.png',
      sun_blind_thrall: 'portraits/sun_blind_thrall.png',
      rootling_husk: 'portraits/rootling_husk.png',
      gilded_sentinel: 'portraits/gilded_sentinel.png',
      vigil_unsleeping: 'portraits/vigil_unsleeping.png',
      what_the_roots_found: 'portraits/what_the_roots_found.png',
    },
    backgrounds: {
      asylum: 'backgrounds/asylum.png',
      burg: 'backgrounds/burg.png',
      depths: 'backgrounds/depths.png',
      anor: 'backgrounds/anor.png',
      kiln: 'backgrounds/kiln.png',
      everlasting_dragon: 'backgrounds/everlasting_dragon.png',
      witch_of_izalith: 'backgrounds/witch_of_izalith.png',
      darkwraith: 'backgrounds/darkwraith.png',
      gravelord_servant: 'backgrounds/gravelord_servant.png',
      map: 'backgrounds/map.png',
      gacha: 'backgrounds/gacha.png',
      characters: 'backgrounds/characters.png',
      inventory: 'backgrounds/inventory.png',
      covenants: 'backgrounds/covenants.png',
      events: 'backgrounds/events.png',
      mail: 'backgrounds/mail.png',
      achievements: 'backgrounds/achievements.jpg',
      shop: 'backgrounds/shop.jpg',
      fortress: 'backgrounds/fortress.png',
      cosmos: 'backgrounds/cosmos.png',
      oolacile: 'backgrounds/oolacile.png',
    },
    ritual: {
      1: 'ritual/tier1.png',
      2: 'ritual/tier2.png',
      3: 'ritual/tier3.png',
      4: 'ritual/tier4.png',
      5: 'ritual/tier5.png',
    },
    // Video takes over from the static tier art above when present — see
    // ritualVideo() below and playRitual() in gacha-ui.js, which checks video
    // first and only falls back to the static image if a tier has no video yet.
    // All five tiers now have their own clip (see assets/ritual/).
    ritualVideo: {
      1: 'ritual/tier1.mp4',
      2: 'ritual/tier2.mp4',
      3: 'ritual/tier3.mp4',
      4: 'ritual/tier4.mp4',
      5: 'ritual/tier5.mp4',
    },
    elements: {
      Physical: 'icons/elements/physical.png',
      Fire: 'icons/elements/fire.png',
      Frost: 'icons/elements/frost.png',
      Lightning: 'icons/elements/lightning.png',
      Magic: 'icons/elements/magic.png',
      Dark: 'icons/elements/dark.png',
      Holy: 'icons/elements/holy.png',
    },
    currency: {
      souls: 'icons/currency/souls.png',
      estus: 'icons/currency/estus.png',
      humanity: 'icons/currency/humanity.png',
      signs: 'icons/currency/signs.png',
      shards: 'icons/currency/shards.png',
    },
    relics: {
      warrior_of_sunlight: 'icons/relics/warrior_of_sunlight.png',
      way_of_white: 'icons/relics/way_of_white.png',
      darkwraith: 'icons/relics/darkwraith.png',
      chaos_servant: 'icons/relics/chaos_servant.png',
      path_of_the_dragon: 'icons/relics/path_of_the_dragon.png',
      princess_guard: 'icons/relics/princess_guard.png',
      gravelord_servant: 'icons/relics/gravelord_servant.png',
      blades_of_the_darkmoon: 'icons/relics/blades_of_the_darkmoon.png',
    },
    relicPieces: {
      warrior_of_sunlight: {
        helm: 'icons/relics/pieces/warrior_of_sunlight_helm.png',
        armor: 'icons/relics/pieces/warrior_of_sunlight_armor.png',
        ring: 'icons/relics/pieces/warrior_of_sunlight_ring.png',
        talisman: 'icons/relics/pieces/warrior_of_sunlight_talisman.png',
      },
      way_of_white: {
        helm: 'icons/relics/pieces/way_of_white_helm.png',
        armor: 'icons/relics/pieces/way_of_white_armor.png',
        ring: 'icons/relics/pieces/way_of_white_ring.png',
        talisman: 'icons/relics/pieces/way_of_white_talisman.png',
      },
      darkwraith: {
        helm: 'icons/relics/pieces/darkwraith_helm.png',
        armor: 'icons/relics/pieces/darkwraith_armor.png',
        ring: 'icons/relics/pieces/darkwraith_ring.png',
        talisman: 'icons/relics/pieces/darkwraith_talisman.png',
      },
      chaos_servant: {
        helm: 'icons/relics/pieces/chaos_servant_helm.png',
        armor: 'icons/relics/pieces/chaos_servant_armor.png',
        ring: 'icons/relics/pieces/chaos_servant_ring.png',
        talisman: 'icons/relics/pieces/chaos_servant_talisman.png',
      },
      path_of_the_dragon: {
        helm: 'icons/relics/pieces/path_of_the_dragon_helm.png',
        armor: 'icons/relics/pieces/path_of_the_dragon_armor.png',
        ring: 'icons/relics/pieces/path_of_the_dragon_ring.png',
        talisman: 'icons/relics/pieces/path_of_the_dragon_talisman.png',
      },
      princess_guard: {
        helm: 'icons/relics/pieces/princess_guard_helm.png',
        armor: 'icons/relics/pieces/princess_guard_armor.png',
        ring: 'icons/relics/pieces/princess_guard_ring.png',
        talisman: 'icons/relics/pieces/princess_guard_talisman.png',
      },
      gravelord_servant: {
        helm: 'icons/relics/pieces/gravelord_servant_helm.png',
        armor: 'icons/relics/pieces/gravelord_servant_armor.png',
        ring: 'icons/relics/pieces/gravelord_servant_ring.png',
        talisman: 'icons/relics/pieces/gravelord_servant_talisman.png',
      },
      blades_of_the_darkmoon: {
        helm: 'icons/relics/pieces/blades_of_the_darkmoon_helm.png',
        armor: 'icons/relics/pieces/blades_of_the_darkmoon_armor.png',
        ring: 'icons/relics/pieces/blades_of_the_darkmoon_ring.png',
        talisman: 'icons/relics/pieces/blades_of_the_darkmoon_talisman.png',
      },
    },
    statuses: {
      burn: 'icons/statuses/burn.png',
      bleed: 'icons/statuses/bleed.png',
      poison: 'icons/statuses/poison.png',
      shock: 'icons/statuses/shock.png',
      curse: 'icons/statuses/curse.png',
      blind: 'icons/statuses/blind.png',
      freeze: 'icons/statuses/freeze.png',
      hex: 'icons/statuses/hex.png',
      atkUp: 'icons/statuses/atkUp.png',
      atkDown: 'icons/statuses/atkDown.png',
      defUp: 'icons/statuses/defUp.png',
      defDown: 'icons/statuses/defDown.png',
      spdUp: 'icons/statuses/spdUp.png',
      spdDown: 'icons/statuses/spdDown.png',
      vulnerability: 'icons/statuses/vulnerability.png',
      dmgUp: 'icons/statuses/dmgUp.png',
      evasionUp: 'icons/statuses/evasionUp.png',
      taunt: 'icons/statuses/taunt.png',
      counterStance: 'icons/statuses/counterStance.png',
      judgment: 'icons/statuses/judgment.png',
      immobilize: 'icons/statuses/immobilize.png',
      curseToken: 'icons/statuses/curseToken.png',
    },
    paths: {
      Warrior: 'icons/paths/Warrior.png',
      Sentinel: 'icons/paths/Sentinel.png',
      Assassin: 'icons/paths/Assassin.png',
      Mage: 'icons/paths/Mage.png',
      Cleric: 'icons/paths/Cleric.png',
      Herald: 'icons/paths/Herald.png',
      Occultist: 'icons/paths/Occultist.png',
    },
    hub: {
      flame: 'icons/hub/flame.png',
      expedition: 'icons/hub/expedition.png',
      summoning: 'icons/hub/summoning.png',
      company: 'icons/hub/company.png',
      bottomless_box: 'icons/hub/bottomless_box.png',
      travelers: 'icons/hub/travelers.png',
      tidings: 'icons/hub/tidings.png',
      deliveries: 'icons/hub/deliveries.png',
      settings: 'icons/hub/settings.png',
      covenants: 'icons/hub/covenants.png',
      achievements: 'icons/hub/achievements.png',
      shop: 'icons/hub/shop.png',
      fortress: 'icons/hub/fortress.png',
      oolacile: 'icons/hub/oolacile.png',
    },
    topbar: {
      element_info: 'icons/topbar/element_info.png',
    },
    weapons: {
      zweihander: 'icons/weapons/zweihander.png',
      grant: 'icons/weapons/grant.png',
      dragonslayer_spear: 'icons/weapons/dragonslayer_spear.png',
      moonlight_greatsword: 'icons/weapons/moonlight_greatsword.png',
      sunlight_talisman: 'icons/weapons/sunlight_talisman.png',
      channelers_trident: 'icons/weapons/channelers_trident.png',
      lifehunt_scythe: 'icons/weapons/lifehunt_scythe.png',
      black_knight_halberd: 'icons/weapons/black_knight_halberd.png',
      quelaags_furysword: 'icons/weapons/quelaags_furysword.png',
      dragon_tooth: 'icons/weapons/dragon_tooth.png',
      crest_shield: 'icons/weapons/crest_shield.png',
      black_bow_of_pharis: 'icons/weapons/black_bow_of_pharis.png',
      dark_silver_tracer: 'icons/weapons/dark_silver_tracer.png',
      tin_crystallization_catalyst: 'icons/weapons/tin_crystallization_catalyst.png',
      ascended_pyromancy_flame: 'icons/weapons/ascended_pyromancy_flame.png',
      ivory_talisman: 'icons/weapons/ivory_talisman.png',
      canvas_talisman: 'icons/weapons/canvas_talisman.png',
      grass_crest_shield: 'icons/weapons/grass_crest_shield.png',
      crystal_ring_shield: 'icons/weapons/crystal_ring_shield.png',
      velkas_talisman: 'icons/weapons/velkas_talisman.png',
      gravelord_sword: 'icons/weapons/gravelord_sword.png',
      claymore: 'icons/weapons/claymore.png',
      bastard_sword: 'icons/weapons/bastard_sword.png',
      tower_kite_shield: 'icons/weapons/tower_kite_shield.png',
      silver_knight_shield: 'icons/weapons/silver_knight_shield.png',
      estoc: 'icons/weapons/estoc.png',
      uchigatana: 'icons/weapons/uchigatana.png',
      pyromancy_flame: 'icons/weapons/pyromancy_flame.png',
      chaos_blade: 'icons/weapons/chaos_blade.png',
      thorolund_talisman: 'icons/weapons/thorolund_talisman.png',
      prayer_beads: 'icons/weapons/prayer_beads.png',
      caduceus_round_shield: 'icons/weapons/caduceus_round_shield.png',
      heralds_banner: 'icons/weapons/heralds_banner.png',
      notched_whip: 'icons/weapons/notched_whip.png',
      dark_hand: 'icons/weapons/dark_hand.png',
      short_bow: 'icons/weapons/short_bow.png',
      heater_shield: 'icons/weapons/heater_shield.png',
      talisman: 'icons/weapons/talisman.png',
      broken_straight_sword: 'icons/weapons/broken_straight_sword.png',
      club: 'icons/weapons/club.png',
      longsword: 'icons/weapons/longsword.png',
    },
    items: {
      soul_small: 'icons/items/soul_small.png',
      soul_large: 'icons/items/soul_large.png',
      soul_hero: 'icons/items/soul_hero.png',
      titanite_shard: 'icons/items/titanite_shard.png',
      titanite_large: 'icons/items/titanite_large.png',
      titanite_chunk: 'icons/items/titanite_chunk.png',
      titanite_slab: 'icons/items/titanite_slab.png',
      ember_asc_1: 'icons/items/ember_asc_1.png',
      ember_asc_2: 'icons/items/ember_asc_2.png',
      ember_asc_3: 'icons/items/ember_asc_3.png',
      demon_core: 'icons/items/demon_core.png',
      boss_soul_fragment: 'icons/items/boss_soul_fragment.png',
      relic_dust: 'icons/items/relic_dust.png',
      estus_shard: 'icons/items/estus_shard.png',
      humanity_sprite: 'icons/items/humanity_sprite.png',
      sign_fragment: 'icons/items/sign_fragment.png',
      green_blossom: 'icons/items/green_blossom.png',
      firebomb: 'icons/items/firebomb.png',
      prism_stone: 'icons/items/prism_stone.png',
      charcoal_resin: 'icons/items/charcoal_resin.png',
      frozen_tear: 'icons/items/frozen_tear.png',
      abyss_residue: 'icons/items/abyss_residue.png',
      sunlight_medal: 'icons/items/sunlight_medal.png',
      ring_of_sacrifice: 'icons/items/ring_of_sacrifice.png',
    },
    title: 'title_keyart.png',
    titleLogo: 'title_logo.png',
    // Fortress roguelike mode (js/engine/fortress.js) — hub tile art lives
    // under REGISTRY.hub.fortress instead (same category every other hub tile
    // icon uses); this one's just the per-node-kind glyphs plus the dice and
    // perk-card frame, all generated from the icon prompt library.
    fortress: {
      normal: 'icons/fortress/normal.png',
      elite: 'icons/fortress/elite.png',
      boss: 'icons/fortress/boss.png',
      shop: 'icons/fortress/shop.png',
      forge: 'icons/fortress/forge.png',
      trap: 'icons/fortress/trap.png',
      event: 'icons/fortress/event.png',
      locked: 'icons/fortress/locked.png',
      dice: 'icons/fortress/dice.png',
      cardFrame: 'icons/fortress/card_frame.png',
    },
    // One icon per DS.FORTRESS_PERKS entry (js/data/fortress.js), keyed by
    // perk id. 'p_ember_within' has no file yet and keeps its emoji fallback.
    fortressPerks: {
      p_whetstone: 'icons/fortress/perks/p_whetstone.png',
      p_hardened: 'icons/fortress/perks/p_hardened.png',
      p_sturdy_boots: 'icons/fortress/perks/p_sturdy_boots.png',
      p_sharp_eye: 'icons/fortress/perks/p_sharp_eye.png',
      p_iron_stomach: 'icons/fortress/perks/p_iron_stomach.png',
      p_kindled_spirit: 'icons/fortress/perks/p_kindled_spirit.png',
      p_tempered_nerve: 'icons/fortress/perks/p_tempered_nerve.png',
      p_quick_study: 'icons/fortress/perks/p_quick_study.png',
      p_ashen_vigor: 'icons/fortress/perks/p_ashen_vigor.png',
      p_quickstep: 'icons/fortress/perks/p_quickstep.png',
      p_killing_edge: 'icons/fortress/perks/p_killing_edge.png',
      p_guardians_ward: 'icons/fortress/perks/p_guardians_ward.png',
      p_focused_strikes: 'icons/fortress/perks/p_focused_strikes.png',
      p_adrenal_rush: 'icons/fortress/perks/p_adrenal_rush.png',
      p_iron_skin: 'icons/fortress/perks/p_iron_skin.png',
      p_executioner: 'icons/fortress/perks/p_executioner.png',
      p_first_blood: 'icons/fortress/perks/p_first_blood.png',
      p_vengeful_spirit: 'icons/fortress/perks/p_vengeful_spirit.png',
      p_predators_instinct: 'icons/fortress/perks/p_predators_instinct.png',
      p_skillful_fury: 'icons/fortress/perks/p_skillful_fury.png',
      p_bloodhound_step: 'icons/fortress/perks/p_bloodhound_step.png',
      p_scavengers_luck: 'icons/fortress/perks/p_scavengers_luck.png',
      p_bloodletter: 'icons/fortress/perks/p_bloodletter.png',
      p_sunlight_oath: 'icons/fortress/perks/p_sunlight_oath.png',
      p_breakers_wrath: 'icons/fortress/perks/p_breakers_wrath.png',
      p_grand_ultimatum: 'icons/fortress/perks/p_grand_ultimatum.png',
      p_undying_flame: 'icons/fortress/perks/p_undying_flame.png',
      p_dark_lords_crown: 'icons/fortress/perks/p_dark_lords_crown.png',
      p_crown_of_the_dead: 'icons/fortress/perks/p_crown_of_the_dead.png',
      p_last_ember: 'icons/fortress/perks/p_last_ember.png',
    },
    // One icon per DS.FORTRESS_TRAPS flavor variant, keyed by id.
    fortressTraps: {
      swinging_axes: 'icons/fortress/traps/swinging_axes.png',
      pressure_plate_arrows: 'icons/fortress/traps/pressure_plate_arrows.png',
      collapsing_floor: 'icons/fortress/traps/collapsing_floor.png',
      poison_dart_wall: 'icons/fortress/traps/poison_dart_wall.png',
    },
    // One icon per DS.FORTRESS_EVENTS entry, keyed by id.
    fortressEvents: {
      shrine_nameless_god: 'icons/fortress/events/shrine_nameless_god.png',
      abandoned_cart: 'icons/fortress/events/abandoned_cart.png',
      sealed_well: 'icons/fortress/events/sealed_well.png',
      sleeping_giant: 'icons/fortress/events/sleeping_giant.png',
    },
    // Shared reusable battle VFX frames (not per-entity — see js/ui/vfx.js's
    // serpentBite/cutIn), keyed by frame name rather than a game-data id.
    vfx: {
      serpent_maw_open: 'vfx/serpent_maw_open.png',
    },
  };

  function url(kind, id) {
    const entry = REGISTRY[kind];
    if (!entry) return null;
    const path = typeof entry === 'string' ? entry : entry[id];
    return path ? BASE + path : null;
  }

  function relicPieceUrl(setId, slot) {
    const set = REGISTRY.relicPieces[setId];
    const path = set && set[slot];
    return path ? BASE + path : null;
  }

  DS.Assets = {
    portrait: (id) => url('portraits', id),
    background: (id) => url('backgrounds', id),
    ritual: (tier) => url('ritual', tier),
    ritualVideo: (tier) => url('ritualVideo', tier),
    element: (name) => url('elements', name),
    currency: (name) => url('currency', name),
    relic: (setId) => url('relics', setId),
    relicPiece: (setId, slot) => relicPieceUrl(setId, slot),
    status: (id) => url('statuses', id),
    path: (name) => url('paths', name),
    hub: (name) => url('hub', name),
    topbar: (name) => url('topbar', name),
    weapon: (id) => url('weapons', id),
    item: (id) => url('items', id),
    title: () => url('title', null),
    titleLogo: () => url('titleLogo', null),
    fortress: (kind) => url('fortress', kind),
    fortressPerk: (id) => url('fortressPerks', id),
    fortressTrap: (id) => url('fortressTraps', id),
    fortressEvent: (id) => url('fortressEvents', id),
    vfx: (id) => url('vfx', id),
  };
})();
